### PR TITLE
OneUi5theme

### PR DESCRIPTION
**Pull request by tribalfs**

### CODE REVIEW

**Comment by salvogiangri** [comment]
I've just checked and the color of the drawer header button seems to be the same as before in Samsung's One UI 5 apps. Did you saw it in any other apps than the one I've checked (Contacts/Calendar)?

**Comment by Lemkinator** [comment]
> I've just checked and the color of the drawer header button seems to be the same as before in Samsung's One UI 5 apps. Did you saw it in any other apps than the one I've checked (Contacts/Calendar)?
> 
>  

When color palette enabled even calender and contacts have different colors on my S22U:
contacts:
Screenshot_20221215_104446_Contacts
calendar:
Screenshot_20221215_104507_Calendar
(theme color is light blue)

**Comment by tribalfs** [comment]
Saw it on calendar app and reminder app in SS22 Ultra.   
image
image

**Comment by tribalfs** [comment]
I think drawerlayout  in reminder app is the latest design.

**Comment by Lemkinator** [comment]
> Saw it on calendar app and reminder app in SS22 Ultra. image image

you have to mention that youre using color palette...
Most of the design elements in this lib are not themed as they should be when color palette enabled...

im using this theming meta in order to enable color palette to my apps using this lib:
```<?xml version="1.0" encoding="utf-8"?>
<ThemeMetaData FormatVersion="1.3" GuideVersion="1.4">
    <AppMetaData Name="SeslTester" TargetApi="21" TargetPackageName="de.lemke.oneuisampleapp" VersionCode="1" VersionName="">
        <Include RefName="SESL" />
        <Property Comment="Icon or Text Color" DefaultValue="074d4" DestAttribName="oui_primary_text_color, oui_primary_icon_color, oui_appinfolayout_info_text_color" UID="55" ValueRef="1-11-3" ValueType="Color" />
        <Property Comment="Themed Background Fill Color" DefaultValue="#fffcfcfc" DestAttribName="filled_background_color, oui_appinfolayout_button_bg_color, oui_relative_link_background_color, sesl_dialog_window_background_color_material_dark, sesl_dialog_window_background_color_material_light" UID="555" ValueRef="1-18-1" ValueType="Color" />
        <Property Comment="Selected Tab Text Color" DefaultValue="074d4" DestAttribName="sesl_tablayout_selected_indicator_color_dark, sesl_tablayout_selected_indicator_color_light, sesl_tablayout_selected_text_color_dark, sesl_tablayout_selected_text_color_light" UID="55555" ValueRef="1-11-3" ValueType="Color" />
    </AppMetaData>
</ThemeMetaData>```

**Comment by tribalfs** [comment]
> > Saw it on calendar app and reminder app in SS22 Ultra. image image
> 
> you have to mention that youre using color palette... Most of the design elements in this lib are not themed as they should be when color palette enabled...
> 
> im using this theming meta in order to enable color palette to my apps using this lib:
> 
> ```
> <ThemeMetaData FormatVersion="1.3" GuideVersion="1.4">
>     <AppMetaData Name="SeslTester" TargetApi="21" TargetPackageName="de.lemke.oneuisampleapp" VersionCode="1" VersionName="">
>         <Include RefName="SESL" />
>         <Property Comment="Icon or Text Color" DefaultValue="074d4" DestAttribName="oui_primary_text_color, oui_primary_icon_color, oui_appinfolayout_info_text_color" UID="55" ValueRef="1-11-3" ValueType="Color" />
>         <Property Comment="Themed Background Fill Color" DefaultValue="#fffcfcfc" DestAttribName="filled_background_color, oui_appinfolayout_button_bg_color, oui_relative_link_background_color, sesl_dialog_window_background_color_material_dark, sesl_dialog_window_background_color_material_light" UID="555" ValueRef="1-18-1" ValueType="Color" />
>         <Property Comment="Selected Tab Text Color" DefaultValue="074d4" DestAttribName="sesl_tablayout_selected_indicator_color_dark, sesl_tablayout_selected_indicator_color_light, sesl_tablayout_selected_text_color_dark, sesl_tablayout_selected_text_color_light" UID="55555" ValueRef="1-11-3" ValueType="Color" />
>     </AppMetaData>
> </ThemeMetaData>```
> ```

No, this is applied using the oneui theming metadata. No effect to non-samsung

**Comment by salvogiangri** [comment]
Samsung Color Theme feature is something we currently can't handle in our lib since this is done in system rather than in app. Here's an example of the Samsung Contacts app theme xml and how it themes the drawer header icon:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ThemeMetaData FormatVersion="1.3" GuideVersion="1.4">
    <AppMetaData Name="SecContacts" TargetApi="21" TargetPackageName="com.samsung.android.app.contacts" VersionCode="1" VersionName="">
        <Include RefName="SESL" />
        <!-- ... -->
        <Property Comment="drawer_setting_icon_tint_color" DefaultValue="#ff86898b" DestAttribName="contact_list_drawer_setting_tint_color" DestQualifiers="" UID="12-46-8" ValueRef="1-3-1" ValueType="TintColor" />
        <!-- ... -->
    </AppMetaData>
</ThemeMetaData>
```

Since One UI 4.1.1 the following metadata flags were added to fetch the theming meta xml file from the app itself rather than using the one in system frameworks (this also allows third party apps to use the Samsung theming engine, just like how @Lemkinator is theming his apps):

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application>
        <!-- ... -->
        <meta-data android:name="theming-meta" android:value="meta_012_contacts"/>
        <meta-data android:name="theming-meta-xml" android:resource="@xml/meta_012_contacts"/>
        <!-- ... -->
    </application>
</manifest>
```

**Comment by Lemkinator** [comment]
@tribalfs 
you can just add `oui_drawerlayout_header_icon_color` to the xml, eg.:
```
<Property Comment="Icon or Text Color" DefaultValue="074d4" DestAttribName="oui_primary_text_color, oui_primary_icon_color, oui_appinfolayout_info_text_color, oui_drawerlayout_header_icon_color" UID="55" ValueRef="1-11-3" ValueType="Color" />
```

**Comment by tribalfs** [comment]
Great! Thanks.

**Pull request closed without merging**
